### ISSUE TITLE
ApplicationSet v0.1.0 Release Checklist

### ISSUE THREAD

**Issue by jgwest** [argoproj-labs/applicationset#181]
This issue tracks all the release items required for the upcoming v0.1.0 release. These will be performed on release day, unless otherwise indicated.

## Release Checklist

First, follow the instructions [on the release process RTD docs page](https://argocd-applicationset.readthedocs.io/en/stable/Releasing/).

Once complete, this is a set of checks to perform once you have a commit, tags, release, docs, and container image.

#### Once you have completed a release, the following should be true:
- [x] A `release-(numbered version)` branch exists in `argoproj-labs/applicationset`
    - example: 'release-0.1.0'
    - [x] The release branch name should NOT contain the letter `v `(e.g. BAD: `release-v0.1.0`, not like this!)
    - [x] Confirm that, within the GitHub web UI, the branch says `This branch is 1 commit ahead of master. `, with that one commit being the release commit described below.

- A release commit exists as the most recent commit of the `release-(version)` branch:
    - [x]  A commit with the message of `Release (version)`
        - Example: `Release v0.1.0`
        - The version string SHOULD contain the letter `v`, as above. 
    - The commit should contain changes to:
        - [x] `manifests/install.yaml`
        - [x] `manifests/install-with-argo-cd.yaml`
        - [x] `manifests/base/kustomization.yaml`
        - [x] `.github/workflows/ci-build.yaml`
        - [x] `docs/Geting-Started.md`
        - [x] `hack/verify-argo-cd-versions.sh`
        - [x] `manifests/namespace-install-with-argo-cd/kustomization.yaml`
- [x] A `v(version)` tag exists in the `argoproj-labs/applicationset` repo
    - Example: `v0.1.0`
    - [x] Ensure it matches the release commit above
- [x] A `stable` tag exists, and points to the same release commit as above.

- [x] Ensure that a GitHub `v(version)` GitHub Release exists, pointing to the `v(version)` tag.
    - Tag must have `v` prefix, eg `v0.1.0`

- [x] Ensure that container image exists on quay.io with name 'argocdapplicationset/argocd-applicationset' 
    - [x] Appears here: https://quay.io/repository/argocdapplicationset/argocd-applicationset?tab=tags
    - [x] With tag `v(version)`, eg `v0.1.0`
        - [x] Tag must have `v` prefix, eg `v0.1.0`
    - [x] Verify that the tag update time references today's date

#### On the `release-0.1.0` branch:

- [x] Ensure the VERSION string matches the expected version
    - [x] The VERSION string should NOT begin with a `v`, (eg BAD: `v0.1.0`)
- [x] Ensure that kustomize.yaml under `manifests/namespace-install-with-argo-cd/kustomization.yaml` points to the desired Argo CD version. 
- [x] Ensure that `install.yaml` and `install-with-argo-cd.yaml` under `manifests/` points to the desired ApplicationSet version.
- [x] Ensure that `install.yaml` and `install-with-argo-cd.yaml` under `manifests/` points to the desired Argo CD version.

## Master branch checklist

- Ensure that a PR is opened on the **master** branch that:
    - [x] Increments the VERSION file (eg 0.1.0 to 0.2.0)
    - [x] Verify VERSION file does not contain the letter `v` as a prefix to the version umber

## Doc checklist
- [x] Ensure that https://readthedocs.org/projects/argocd-applicationset/versions/ points to the correct commit (commit that is at the HEAD of the release branch), for the `stable` and `v0.1.0` versions.
- [x] Ensure that https://argocd-applicationset.readthedocs.io/ points to the new version, and contains the correct content 
    - **Note**: this may require a manually triggered build at rtd.io
- [x] Ensure that the Getting Start page at rtd.io includes references to `kubectl apply` which points to the correct applicationset controller version
    - On [Stable](https://argocd-applicationset.readthedocs.io/en/stable/Geting-Started/)
    - On the version-specific page: `https://argocd-applicationset.readthedocs.io/en/(version)/Geting-Started/`
        - Example: `https://argocd-applicationset.readthedocs.io/en/v0.1.0/Geting-Started/`

#### In the GitHub Releases tag:
- [x] Ensure that the `v(version string)` release contains the features/change log for the particular version. This should be roughly the same content as goes into the CHANGELOG.md file.

#### On the `release-(version)` branch:    
- [x] Ensure that CHANGELOG.md includes the new version information
	
#### On the master branch:
- [x] Ensure that CHANGELOG.md includes the new version information

## Live image testing

- [x] Apply `install.yaml` on a cluster, and confirm that it installs the correct image version
    - [x] Confirm that all the pods start as expected.
    - [x] Confirm that the pod logs contain no errors
    - [x] Run ApplicationSet E2E tests against ApplicationSet controller installed via this method
    - [x] Confirm that the pod logs contain no errors after runnings the tests

- [x] Apply `install-with-argo-cd.yaml` on a cluster, and confirm that it installs the correct image version
    - [x] Confirm that all the pods start as expected.
    - [x] Confirm that the pod logs contain no errors
    - [x] Run ApplicationSet E2E tests against ApplicationSet controller installed via this method
    - [x] Confirm that the pod logs contain no errors after runnings the tests

## Communications

- [x] Publish blog post
- [x] Post to slack

**Comment by jgwest** [comment]
:tada: :tada: :tada: :tada:
